apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-nginx-dev

resources:
- deployment.yaml
- service.yaml

images:
- name: ghcr.io/ghkim-devstack/github-actions-argocd-test
  newName: ghcr.io/ghkim-devstack/github-actions-argocd-test
  newTag: "23727e4"
