apiVersion: v1
kind: Service
metadata:
  name: github-actions-nginx
  namespace: gitops-nginx-dev
spec:
  type: NodePort
  selector:
    app: github-actions-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081
